/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4125project;
import java.sql.*;
import static javafx.scene.input.KeyCode.J;
import javax.swing.*;
/**
 *
 * @author Jay
 */
public class AddJob extends javax.swing.JFrame {
    Connection conn;
    public AddJob(Connection conn) throws SQLException {
        initComponents();
        this.conn = conn;
        Statement statement = conn.createStatement();
        ResultSet profile = statement.executeQuery("SELECT distinct pos_code from job_profile");
        while(profile.next()){
            String value = profile.getString("pos_code");
            poscodeCombo.addItem(value);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLabel = new javax.swing.JLabel();
        jobcodeText = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        jobtypeCombo = new javax.swing.JComboBox<>();
        GenderLabel = new javax.swing.JLabel();
        ZipLabel = new javax.swing.JLabel();
        payrateText = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        paytypeCombo = new javax.swing.JComboBox<>();
        poscodeCombo = new javax.swing.JComboBox<>();

        setTitle("JOB");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setResizable(false);

        IDLabel.setText("Job Code");

        jobcodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobcodeTextActionPerformed(evt);
            }
        });

        NameLabel.setText("Pos Code");

        EmailLabel.setText("Job Type");

        jobtypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "salary", "wage" }));
        jobtypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobtypeComboActionPerformed(evt);
            }
        });

        GenderLabel.setText("Pay Rate");

        ZipLabel.setText("Pay Type");

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        paytypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "full-time", "part-time" }));

        poscodeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>" }));
        poscodeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poscodeComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ZipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GenderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jobcodeText)
                            .addComponent(payrateText)
                            .addComponent(jobtypeCombo, 0, 107, Short.MAX_VALUE)
                            .addComponent(paytypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poscodeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(AddButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(jobcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(poscodeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(jobtypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(payrateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paytypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipLabel))
                .addGap(24, 24, 24)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jobcodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobcodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobcodeTextActionPerformed

    private void jobtypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobtypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobtypeComboActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        try{
            Statement statement = this.conn.createStatement();
            String Query = "INSERT INTO job (JOB_CODE, POS_CODE, JOB_TYPE, PAY_RATE, PAY_TYPE) VALUES ('"+jobcodeText.getText()+"','"+poscodeCombo.getSelectedItem()+"','"+jobtypeCombo.getSelectedItem()+"','"+payrateText.getText()+"','"+paytypeCombo.getSelectedItem()+"')";
            statement.execute(Query);
            JOptionPane.showMessageDialog(null, "Successfully Added");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        jobcodeText.setText(null);
        poscodeCombo.setSelectedItem("<select>");
        jobtypeCombo.setSelectedItem("<select>");
        payrateText.setText(null);
        paytypeCombo.setSelectedItem("<select>");
    }//GEN-LAST:event_AddButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        try{
            Statement statement = this.conn.createStatement();
            String Query = "DELETE FROM job WHERE job_code = '"+jobcodeText.getText()+"'";
            statement.execute(Query);
            JOptionPane.showMessageDialog(null, "Successfully Removed");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void poscodeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poscodeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poscodeComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            try{
                    String url = "jdbc:oracle:thin:@dbsvcs.cs.uno.edu:1521:orcl";
                    String username = "cmaryan";
                    String password = "tpmFR3NV";
                    Connection conn = DriverManager.getConnection(url,username,password);
                    new AddJob(conn).setVisible(true);
            }catch(SQLException e){
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JTextField jobcodeText;
    private javax.swing.JComboBox<String> jobtypeCombo;
    private javax.swing.JTextField payrateText;
    private javax.swing.JComboBox<String> paytypeCombo;
    private javax.swing.JComboBox<String> poscodeCombo;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
